具体时间:[2020-02-23 00:46:09,857][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:46:10,860][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:46:12,198][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:46:12,725][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:50:05,508][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:50:06,525][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:50:07,286][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:50:07,832][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:51:14,772][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:51:15,923][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:54:12,022][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:54:14,137][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 03:18:33,332][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
具体时间:[2020-02-23 03:18:34,495][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
具体时间:[2020-02-23 03:18:35,889][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
具体时间:[2020-02-23 03:18:37,289][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Program Files\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
具体时间:[2020-02-23 13:15:31,312][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-23 13:15:37,821][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

具体时间:[2020-02-24 00:27:18,916][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-24 00:27:25,795][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

具体时间:[2020-02-24 00:29:50,200][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-24 00:29:56,909][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

具体时间:[2020-02-24 00:43:50,492][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-24 00:43:57,931][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-24 00:44:07,823][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

具体时间:[2020-02-24 00:52:29,099][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-24 00:52:40,564][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

具体时间:[2020-02-24 00:53:08,423][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-24 00:56:38,547][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

具体时间:[2020-02-24 00:58:07,640][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-24 00:58:14,544][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

具体时间:[2020-02-24 00:58:26,536][default:INFO(156)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第156行]-登录成功

