具体时间:[2021-05-23 09:01:21,095][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2021-05-23 09:01:21,682][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2021-05-23 09:01:27,336][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 09:11:08,175][default:ERROR(252)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第252行]-[Error in Lib.Utils] msg: 'keyCabinet' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'keyCabinet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 84, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'keyCabinet' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'keyCabinet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 248, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 88, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'keyCabinet' is not a registered namespace
具体时间:[2021-05-23 09:24:46,728][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2021-05-23 09:24:55,561][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2021-05-23 09:25:01,986][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2021-05-23 09:25:03,595][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2021-05-23 09:25:11,792][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 09:29:11,841][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 11:23:27,013][default:ERROR(252)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第252行]-[Error in Lib.Utils] msg: Reverse for 'mapIndex' not found. 'mapIndex' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py", line 84, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Program Files\Python36\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'mapIndex' not found. 'mapIndex' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\Lib\Utils.py", line 248, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py", line 88, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Program Files\Python36\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'mapIndex' not found. 'mapIndex' is not a valid view function or pattern name.
具体时间:[2021-05-23 14:38:39,095][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 16:03:32,564][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 17:03:57,776][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 18:48:52,556][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 18:50:32,546][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2021-05-23 18:50:37,734][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

具体时间:[2021-05-23 19:52:23,139][default:INFO(181)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage_yanshi\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第181行]-登录成功

